#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --quiet -- eslintrc.json; then
  echo "Linting the entire project because eslintrc.json has changed."
  npx eslint --fix .
else
  echo "No changes in eslintrc.json"
fi

npx lint-staged
npm run test
